### ISSUE TITLE
移动根节点会出现拉伸的情况

### ISSUE THREAD

**Issue by billsinla** [EZhex1991/EZPhysicsBone#1]
![图片](https://user-images.githubusercontent.com/15274049/59588311-e4c77e80-9119-11e9-9245-2c1d4c49263c.png)

**Comment by EZhex1991** [comment]
这是因为我在外围加了InsideCapsule的碰撞，静态节点可以被拉出碰撞体外，但是动态节点不行。

**Comment by billsinla** [comment]
大佬，请教一下圆柱 和 圆柱的碰撞 有什么可以参考的算法吗

**Comment by EZhex1991** [comment]
可以参考胶囊的计算方式https://github.com/EZhex1991/EZPhysicsBone/blob/19f63fc7edbf2d230cde62ce98a1ca78fcf476c1/Runtime/EZPhysicsBoneUtility.cs#L92-L115

**Comment by billsinla** [comment]
> 
> 
> 可以参考胶囊的计算方式
> 
> https://github.com/EZhex1991/EZPhysicsBone/blob/19f63fc7edbf2d230cde62ce98a1ca78fcf476c1/Runtime/EZPhysicsBoneUtility.cs#L92-L115

嗯嗯，get 到了，感激！！！！！

**Comment by EZhex1991** [comment]
> > 可以参考胶囊的计算方式
> > https://github.com/EZhex1991/EZPhysicsBone/blob/19f63fc7edbf2d230cde62ce98a1ca78fcf476c1/Runtime/EZPhysicsBoneUtility.cs#L92-L115
> 
> 嗯嗯，get 到了，感激！！！！！

https://github.com/EZhex1991/EZPhysicsBone/blob/master/Runtime/EZPBColliderCylinder.cs
单独实现了一个Cylinder的碰撞，你可以参考一下

**Comment by billsinla** [comment]
> 
> 
> > > 可以参考胶囊的计算方式
> > > https://github.com/EZhex1991/EZPhysicsBone/blob/19f63fc7edbf2d230cde62ce98a1ca78fcf476c1/Runtime/EZPhysicsBoneUtility.cs#L92-L115
> > 
> > 
> > 嗯嗯，get 到了，感激！！！！！
> 
> https://github.com/EZhex1991/EZPhysicsBone/blob/master/Runtime/EZPBColliderCylinder.cs
> 单独实现了一个Cylinder的碰撞，你可以参考一下

感谢！！！！我也正在学习您分享的动态骨骼！！ 受益匪浅
