### ISSUE TITLE
2DSpirteBone 不兼容，表现为原地不动

### ISSUE THREAD

**Issue by K4N114** [EZhex1991/EZPhysicsBone#10]
现在的效果并不支持Unity官方2DSprite骨骼，在Editor中观察到骨骼有运动但贴图未改变。
原因是在Update中回退了骨骼，2D骨骼的刷新逻辑也是在Update中，因此对它来说Transform并没有变化。
已经验证的解决方案：
1、将<RevertTransforms(startDepth);>移动到<LateUpdate()>，会导致闪烁问题，不建议使用。
2、在ProjectSetting中改变代码执行顺序，使其更早执行。

顺便感谢分享，非常好代码，使我根骨骼旋转！

**Comment by EZhex1991** [comment]
之前为了实现在原有动画帧的效果上叠加柔性表现，所以把执行顺序调整到比较靠后了。既保证动画效果又保证sprite显示正常目前看来没有完美的解决办法。

你的解决方案可行，其他与内置组件冲突的情况也可以参考解决。
