### ISSUE TITLE
大佬，关于bend spring 算法的添加思路

### ISSUE THREAD

**Issue by billsinla** [EZhex1991/EZPhysicsBone#2]
我想要试试约束有间隔的两点
![图片](https://user-images.githubusercontent.com/15274049/59921870-a9061f00-9461-11e9-812a-82f8e13fae57.png)
哈哈，感觉越来越像布料了
我尝试在 PhysicsBone 的 Siblings 部分添加
对leftSibling的leftSibling 和 rightSibling 的 rightSibling做长度约束
这块直接就炸裂了。。。。

**Comment by billsinla** [comment]
![图片](https://user-images.githubusercontent.com/15274049/59924239-e53c7e00-9467-11e9-8ca0-ce5b5f8d92b2.png)
附上我丑陋的示意图
我想搞成类似弹簧效果把两侧弹出来
感觉我有点作死

**Comment by EZhex1991** [comment]
> ![图片](https://user-images.githubusercontent.com/15274049/59924239-e53c7e00-9467-11e9-8ca0-ce5b5f8d92b2.png)
> 附上我丑陋的示意图
> 我想搞成类似弹簧效果把两侧弹出来
> 感觉我有点作死

才看到这个issue。。。想法应该没问题。我的代码里每个节点都是根据关联的节点来移动自身，如果要做bend spring，那直接复制sibling的代码应该就行。最好是先用Gizmos把关联结构全画出来，没问题了再尝试做计算。
