### ISSUE TITLE
能兼容2017.1吗

### ISSUE THREAD

**Issue by Anjiu464** [EZhex1991/EZPhysicsBone#3]
大佬您好，这是我见过最实用的的动力学模拟了；用过dy、spring、swing等等都不如你这款；现在遇到一个问题，导入17.1后报错更改类似的api后效果完全不对，很希望大佬能兼容一波，谢谢~~~

**Comment by EZhex1991** [comment]
十一假期后会考虑兼容到2017.1.5 (UnityHub2.1上能找到的最老的版本了)，不过还是建议升级Unity到2017.4 (LTS) 版本。

**Comment by EZhex1991** [comment]
已经处理，使用2017.1.5提交的，AssetStore的版本暂时不会更新
https://github.com/EZhex1991/EZPhysicsBone/commit/be9c6677d8d0418bb5ddcbe8216bbd8a499e739d
