### ISSUE TITLE
软骨的根骨骼不会旋转

### ISSUE THREAD

**Issue by wdw89** [EZhex1991/EZPhysicsBone#7]
我测试发现EZSoftBone软骨的根骨骼不会旋转，导致裙子容易和大腿穿插，但试了其他软骨插件软骨根骨骼都会旋转的

**Comment by EZhex1991** [comment]
把它的父物体当作根骨骼就可以解决了，如果父物体有多个子物体，把不需要动态的子物体给到EndBones。

EZSoftBone的计算方式是自顶向下的形变计算和延迟还原。所以我默认根骨骼是运动的数据来源，不由EZSoftBone去控制。
至于其他插件可以做到，我觉得和设计不同有关。如果可以提供动图参考我可以分析分析优劣。

**Comment by wdw89** [comment]
https://github.com/unity3d-jp/UnityChanSpringBone
https://github.com/SPARK-inc/SPCRJointDynamics
对比的是UnityChanSpringBone和SPCRJointDynamics这两个插件。UnityChanSpringBone是根据子骨骼的位移来计算出父骨骼的旋转。SPCRJointDynamics好像是另一种计算。
EndBones是用来排除的啊，之前一直没搞明白。
